CREATE TABLESPACE actividad2 DATAFILE 'actividad2.dbf' SIZE 1m;
CREATE USER actividad2 IDENTIFIED BY actividad2 DEFAULT TABLESPACE actividad2;
GRANT UNLIMITED TABLESPACE TO actividad2;
GRANT CREATE SESSION TO actividad2;
GRANT CREATE TABLE TO actividad2;