--------------------------------------------------------
-- Archivo creado  - martes-marzo-30-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITIES
--------------------------------------------------------

  CREATE TABLE "ACTIVIDAD2"."CITIES" 
   (	"ID" VARCHAR2(36 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"REGION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2" ;
--------------------------------------------------------
--  DDL for Table GARDENS
--------------------------------------------------------

  CREATE TABLE "ACTIVIDAD2"."GARDENS" 
   (	"ID" VARCHAR2(36 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EXTENSION" NUMBER, 
	"CITY_ID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2" ;
REM INSERTING into ACTIVIDAD2.CITIES
SET DEFINE OFF;
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('dfd97ecf-54c4-4ab4-a71a-f0677df3edfc','Zaragoza','Aragon');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('31fb9d61-15e9-4f04-a390-d05d7632964d','Huesca','Aragon');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('a804b6c1-b4f5-4b85-85f3-109b2e3cf18c','Teruel','Aragon');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('8f398910-2fec-48b8-8663-8ea4a05a77f4','Barcelona','Cataluoa');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('811bd2f8-8ebb-48f4-b128-5902eb3152bb','Gerona','Cataluoa');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('52778f34-9fb7-4c29-9450-0caa138caf0b','Sevilla','Andalucoa');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('26ff3c0b-536d-477f-a58d-3650a17b0be6','Cordoba','Andalucoa');
Insert into ACTIVIDAD2.CITIES (ID,NAME,REGION) values ('bec930b2-17ee-4996-9814-a6698bf0e8d4','Madrid','Madrid');
REM INSERTING into ACTIVIDAD2.GARDENS
SET DEFINE OFF;
Insert into ACTIVIDAD2.GARDENS (ID,NAME,EXTENSION,CITY_ID) values ('7bfec9d4-a2f9-4320-9832-1c9ceeeabdcf','park2 zaragoza','22','dfd97ecf-54c4-4ab4-a71a-f0677df3edfc');
Insert into ACTIVIDAD2.GARDENS (ID,NAME,EXTENSION,CITY_ID) values ('459d1840-52df-4e2b-b1a9-e9a41deac586','park1 barcelona','33','8f398910-2fec-48b8-8663-8ea4a05a77f4');
--------------------------------------------------------
--  DDL for Index CITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACTIVIDAD2"."CITIES_PK" ON "ACTIVIDAD2"."CITIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2" ;
--------------------------------------------------------
--  DDL for Index GARDENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACTIVIDAD2"."GARDENS_PK" ON "ACTIVIDAD2"."GARDENS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2" ;
--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "ACTIVIDAD2"."CITIES" ADD CONSTRAINT "CITIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2"  ENABLE;
  ALTER TABLE "ACTIVIDAD2"."CITIES" MODIFY ("REGION" NOT NULL ENABLE);
  ALTER TABLE "ACTIVIDAD2"."CITIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ACTIVIDAD2"."CITIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GARDENS
--------------------------------------------------------

  ALTER TABLE "ACTIVIDAD2"."GARDENS" ADD CONSTRAINT "GARDENS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ACTIVIDAD2"  ENABLE;
  ALTER TABLE "ACTIVIDAD2"."GARDENS" MODIFY ("CITY_ID" NOT NULL ENABLE);
  ALTER TABLE "ACTIVIDAD2"."GARDENS" MODIFY ("EXTENSION" NOT NULL ENABLE);
  ALTER TABLE "ACTIVIDAD2"."GARDENS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ACTIVIDAD2"."GARDENS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GARDENS
--------------------------------------------------------

  ALTER TABLE "ACTIVIDAD2"."GARDENS" ADD CONSTRAINT "GARDENS_FK1" FOREIGN KEY ("CITY_ID")
	  REFERENCES "ACTIVIDAD2"."CITIES" ("ID") ON DELETE SET NULL ENABLE;
